### ISSUE TITLE
pg is not available during auth

### ISSUE THREAD

**Issue by mikejerome** [jedireza/hapi-node-postgres#12]
It would be nice to be able to use pg on the request object inside an auth strategy. By attaching at preAuth instead of preHandler it becomes possible to use request.pg.client inside the auth strategy.

**Comment by jedireza** [comment]
Thanks for opening an issue. You can pass an option to control which mount point pg will be available in. See: https://github.com/jedireza/hapi-node-postgres#usage

**Comment by mikejerome** [comment]
Awesome, thank you.
