### ISSUE TITLE
[enhancement] Multiple dbs connections

### ISSUE THREAD

**Issue by doron2402** [jedireza/hapi-node-postgres#25]
Hi Reza,
I'm currently working with multiple Postgresql databases and would like to use the same pool connection, is that something you'll be interesting on expanding the module to handle?

Thanks,

**Comment by jedireza** [comment]
Yeah this sounds interesting. I'm unsure if they'd be able to share the same pool, granted I haven't looked into it myself. Let me know what you come up with.

**Comment by doron2402** [comment]
end up building [this](https://github.com/doron2402/hapi-postgres-pool) I'll see how it performs.
my concerns are opening all the connection on every request coming in.
